# Caja settings. Restore with: caja-dconf-load  (dconf load /org/mate/ < this file)
# Regenerate after changing prefs: caja-dconf-dump

[caja/list-view]
default-column-order=['name', 'size', 'type', 'date_modified', 'date_accessed', 'date_created', 'extension', 'group', 'where', 'mime_type', 'octal_permissions', 'owner', 'permissions', 'size_on_disk']
default-visible-columns=['name', 'size', 'type', 'date_modified', 'permissions']

[caja/preferences]
always-use-location-entry=true
ctrl-tab-switch-tabs=true
date-format='iso'
default-folder-viewer='list-view'
exit-with-last-window=true
show-hidden-files=true
thumbnail-limit=uint64 104857600
use-iec-units=true

[caja/sidebar-panels/tree]
show-only-directories=false


[applications-terminal]
exec='kitty'

[background]
show-desktop-icons=false
